<?php
/**
 * Created by PhpStorm.
 * User: viktor
 * Date: 08.02.2016
 * Time: 17:37
 */

namespace frontend\components\sitemap;
use himiklab\sitemap\Sitemap;

class Sitemapchild extends Sitemap
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function buildSitemap()
    {
        return parent::buildSitemap(); // TODO: Change the autogenerated stub
    }

}