<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{attribute}" must be a valid JSON' => '',
    'About ID' => '',
    'AboutPage ID' => '',
    'After body' => '',
    'Base URL' => '',
    'Before body' => '',
    'Body' => '',
    'Caption' => '',
    'Carousel ID' => '',
    'Categories list' => '',
    'Category ID' => '',
    'Client ID' => '',
    'Comment' => '',
    'Component' => '',
    'Config' => '',
    'Down to maintenance.' => '',
    'E-mail' => '',
    'Finance ID' => '',
    'FinancePage ID' => '',
    'Firstname' => '',
    'Gender' => '',
    'Head' => '',
    'ID' => '',
    'Image' => '',
    'Info ID' => '',
    'Key' => '',
    'Locale' => '',
    'Locale Group ID' => '',
    'Member ID' => '',
    'Model ID' => '',
    'On scenario' => '',
    'Parent Category' => '',
    'Path' => '',
    'Photo' => '',
    'Picture' => '',
    'Project ID' => '',
    'Promo ID' => '',
    'Service ID' => '',
    'ServicePage ID' => '',
    'Show on about page' => '',
    'Size' => '',
    'Updater' => '',
    'Upload Ip' => '',
    'User ID' => '',
    'About' => 'Про компанію',
    'Active' => 'Активно',
    'Article ID' => 'ID статті',
    'Author' => 'Автор',
    'Base Url' => 'Лінк',
    'Category' => 'Категорія',
    'Created At' => 'Дата створення',
    'Created at' => 'Дата створення',
    'Dealer ID' => 'ID дилера',
    'Deleted' => 'Видалено',
    'Description' => 'Опис',
    'Domain ID' => 'ID дилера',
    'File Type' => 'Тип файлу',
    'Finance' => 'Фiнанси',
    'Last login' => 'Останній вхід',
    'Lastname' => 'Прізвище',
    'Middlename' => 'По батькові',
    'Model' => 'Модель',
    'Name' => 'Ім\'я',
    'Order' => 'Порядок',
    'Position' => 'Позиція',
    'Price' => 'Ціна',
    'Published' => 'Опубліковано',
    'Published At' => 'Дата публікації',
    'Service' => 'Власникам',
    'Slug' => 'Лінк (відносний)',
    'Status' => 'Статус',
    'Thumbnail' => 'Прев\'ю',
    'Title' => 'Назва',
    'Type' => 'Тип',
    'Updated At' => 'Дата оновлення',
    'Updated at' => 'Дата оновлення',
    'Url' => 'Лінк',
    'Username' => 'Користувач',
    'Value' => 'Значення',
    'Video' => 'Відео',
    'Video mobile' => 'Відео для мобільних',
    'Weight' => 'Порядок',
];
