<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Body' => '',
    'E-mail' => '',
    'Email' => '',
    'Error while oauth process.' => '',
    'Female' => '',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => '',
    'Incorrect username or password.' => '',
    'Log in with' => '',
    'Male' => '',
    'Password reset for {name}' => '',
    'Request password reset' => '',
    'Reset' => '',
    'Reset password' => '',
    'Sign up with' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Subject' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Username or email' => '',
    'Verification Code' => '',
    'We already have a user with email {email}' => '',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '',
    'Your account has been successfully saved' => '',
    '{app-name} | Feedback request from' => '',
    '{app-name} | Your login information' => '',
    'Account Settings' => 'Налаштування аккаунту',
    'Check your email for further instructions.' => 'Перевірте ваш e-mail',
    'Close' => 'Закрити',
    'Confirm Password' => 'Підтвердіть пароль',
    'Create' => 'Створити',
    'Create Domain' => 'Додати дилера',
    'Delete' => 'Видалити',
    'Domains' => 'Дилери',
    'Login' => 'Логін',
    'Name' => 'Ім\'я',
    'Need an account? Sign up.' => 'Потрібен аккаунт? Зареєструйтесь',
    'New password was saved.' => 'Новий пароль збережено',
    'Password' => 'Пароль',
    'Profile settings' => 'Налаштування профілю',
    'Remember Me' => 'Запам\'ятати мене',
    'Search' => 'Пошук',
    'Signup' => 'Увійти',
    'User Settings' => 'Налаштування користувача',
    'Username' => 'Користувач',
    'popupMessage' => 'Спеціально для Ваc<br/> ми зробили мобільну версію!<br/>
Спробуйте!',
];
