<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Book a test drive' => '',
    'Chat with us' => '',
    'Contact us' => '',
    'Dealers nearby' => 'Диллеры рядом',
    'Find a dealer' => '',
    'Hide menu' => '',
    'Latest&#x20;offers' => '',
    'Log out' => '',
    'Menu' => '',
    'Motability' => '',
    'My Renault' => '',
    'New&#x20;Vehicles' => '',
    'Promotions' => 'Акции',
    'RANGE' => 'Модельный ряд',
    'Renaultsport' => '',
    'Rus' => '',
    'Skip to Main Content' => '',
    'Ukr' => '',
    'Used&#x20;Vehicles' => '',
    'renault in Ukraine' => 'renault в Укаине',
    'subscribes' => 'Подписка на новости',
    'About' => 'О нас',
    'Account Settings' => 'Настройки аккаунта',
    'Body' => 'Сообщение',
    'Check your email for further instructions.' => 'Проверьте ваш e-mail.',
    'Confirm Password' => 'Подтвердите пароль',
    'Contact' => 'Контакты',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Ошибка в процессе OAuth авторизации.',
    'Female' => 'Женский',
    'Home' => 'Главная',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Если вы забыли пароль, вы можете сбросить его <a href="{link}">здесь</a>',
    'Incorrect username or password.' => 'Неправильный логин или пароль.',
    'Log in with' => 'Войти с помощью',
    'Login' => 'Вход',
    'Male' => 'Мужской',
    'Name' => 'Имя',
    'Need an account? Sign up.' => 'Нужен аккаунт? Зарегистрируйтесь',
    'New password was saved.' => 'Новый пароль был сохранен',
    'News' => 'Новости',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Сброс пароля для {name}',
    'Portfolio' => 'Кейсы',
    'Profile settings' => 'Настройки профиля',
    'Remember Me' => 'Запомнить меня',
    'Request password reset' => 'Запрос сброса пароля',
    'Reset password' => 'Сброс пароля',
    'Sign up with' => 'Создать аккаунт с помощью',
    'Signup' => 'Регистрация',
    'Sorry, we are unable to reset password for email provided.' => 'Извините, мы не можем сбросить пароль для этого e-mail.',
    'Subject' => 'Тема',
    'This email address has already been taken.' => 'Этот e-mail уже занят',
    'This username has already been taken.' => 'Это имя пользователя уже занято',
    'Update' => 'Редактировать',
    'User Settings' => 'Настройки пользователя',
    'Username' => 'Имя пользователя',
    'Username or email' => 'Имя пользователя или e-mail',
    'Verification Code' => 'Проверочный код',
    'We already have a user with email {email}' => 'Пользователь с email {email} уже зарегистрирован.',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Добро пожаловать в {app-name}. E-mail с информацией о пользователе был отправлен на вашу почту.',
    'Your account has been successfully saved' => 'Ваш аккаунт был успешно сохранен',
    '{app-name} | Your login information' => '{app-name} | Информация о пользователе',
];
